version: "2.37.0"
services:
  web:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/plans
    command: bundle exec rackup --host 0.0.0.0 -p 4567
    ports:
      - "4567:4567"
    environment:
      SINATRA_ENV: ${SINATRA_ENV}
      MONGO_LOCATION: mongodb
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      TZ: America/Sao_Paulo
    depends_on:
      - mongodb
    networks:
      - mongo-compose-network

  mongodb:
    image: mongo:8.0
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: plans_${SINATRA_ENV}
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
    depends_on:
      - mongodb
    networks:
      - mongo-compose-network
    links:
      - mongodb
    volumes:
      - ./data:/data/db

networks:
  mongo-compose-network:
    driver: bridge
